server:
  port: 9004
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://postgres-vehicle:5432/vehicle_db
    username: postgres
  jpa:
    hibernate:
    ddl-auto: create-drop
  application:
    name: vehicle-service
management:
  endpoint:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true