server:
  port: 8080
spring:
  application:
    name: api-gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: false
            lowerCaseServiceId: true
        httpclient:
          connect-timeout: 1000
          response-timeout: 2s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      gateway:
        enabled: true
    info:
      env:
        enabled: true

logging:
  level:
    com:
      transmarket:
        app:
          apigateway: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

resilience4j.circuitbreaker:
  config:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000


