server:
  port: 9001
spring:
  application:
    name: company-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5434/company_db
    username: postgres
  jpa:
    hibernate:
    ddl-auto: create-drop
    generate-ddl: true
  zipkin:
    base-url: http://zipkin:9411
management:
  endpoint:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true