server:
  port: 9002
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5431/user_db
    username: postgres
  jpa:
    hibernate:
    ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  application:
    name: user-service
  zipkin:
    base-url: http://zipkin:9411
management:
  endpoint:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
