services:
  network-deploy-service:
    networks:
      - transmarket
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
  microservice-config-server-config:
    extends:
      service: microservice-base-config
    depends_on:
      config-server:
        condition: service-healthy
    environments:
      SPRING_CONFIG_IMPORT: "config-server:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: dev


